apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: nats-broker
  namespace: nats-test
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
